timeout: 10
default_entry: 1
verbose: yes

:CachyOS (Partition Path /@/boot)
    protocol: linux_x86_64
    kernel_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/@/boot/vmlinuz-linux-cachyos
    module_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/@/boot/amd-ucode.img
    module_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/@/boot/initramfs-linux-cachyos.img
    cmdline: root=UUID=28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a rootflags=subvol=@ rw

:CachyOS (Subvolume Path /boot)
    protocol: linux_x86_64
    kernel_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/boot/vmlinuz-linux-cachyos
    module_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/boot/amd-ucode.img
    module_path: uuid(28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a):/boot/initramfs-linux-cachyos.img
    cmdline: root=UUID=28d17d3f-45b4-4fbb-a11b-4fa4fdd5e99a rootflags=subvol=@ rw